services:
  elasticsearch-1:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.6.0
    container_name: elasticsearch-1
    environment:
      - ELASTICSEARCH_CLUSTER_NAME=es-cluster
      - ELASTICSEARCH_NODE_NAME=elasticsearch-1
      - ELASTICSEARCH_CLUSTER_HOSTS=elasticsearch-1
      - node.name=elasticsearch-1
      - cluster.name=es-docker-cluster
      - cluster.initial_master_nodes=elasticsearch-1
      - xpack.security.enabled=false
      - xpack.security.enrollment.enabled=false
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - elastic

  kibana:
    image: docker.elastic.co/kibana/kibana:8.6.0
    environment:
      ELASTICSEARCH_HOSTS: "http://elasticsearch-1:9200"
    ports:
      - 5601:5601
    networks:
      - elastic

networks:
  elastic:
    driver: bridge