addSbtPlugin("org.scalameta" % "sbt-scalafmt" % "2.4.6")
addSbtPlugin("com.dwijnand"  % "sbt-dynver"   % "4.1.1")
//addSbtPlugin("io.github.davidgregory084" % "sbt-tpolecat"  % "0.4.1")
addSbtPlugin("com.eed3si9n"       % "sbt-buildinfo" % "0.11.0")
addSbtPlugin("ch.epfl.scala"      % "sbt-scalafix"  % "0.10.1")
addSbtPlugin("org.scoverage"      % "sbt-scoverage" % "2.0.1")
addSbtPlugin("pl.project13.scala" % "sbt-jmh"       % "0.4.2")
